"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const http = require("http");
const socket = require("socket.io");
const path = require("path");
const stylus = require("stylus");
const bodyParser = require("body-parser");
const app = express();
const server = http.createServer(app);
const io = socket(server);
const root = __dirname;
const viewsDir = path.join(root, 'views');
const publicDir = path.join(root, 'public');
app.set('view engine', 'pug');
app.set('views', viewsDir);
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(stylus.middleware(publicDir));
app.use(express.static(publicDir));
app.get("/*", (req, res) => res.render("map"));
server.listen(3000);
