"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const http = require("http");
const socket = require("socket.io");
const path = require("path");
const Setup_1 = require("./Setup");
const Config_1 = require("./Config");
const socketHandler_1 = require("./sockets/socketHandler");
const app = express();
const server = http.createServer(app);
const io = socket(server);
const root = __dirname;
const viewsDir = path.join(root, 'views');
const publicDir = path.join(root, 'public');
const db = Setup_1.Setup.setupDatabase(Config_1.Config.db.address, Config_1.Config.db.port, Config_1.Config.db.db, Config_1.Config.db.user.name, Config_1.Config.db.user.password);
Setup_1.Setup.setupAuthGoogle(Config_1.Config.auth.id, Config_1.Config.auth.secret);
Setup_1.Setup.setupExpress(app, __dirname + "/../");
Setup_1.Setup.setupSession(app, io);
Setup_1.Setup.addAuthMiddleware(app);
Setup_1.Setup.addAsMiddleware(app, "db", db);
socketHandler_1.SocketHandler.bindHandlers(app, io);
app.get("*", (req, res) => {
    res.render("map");
});
server.listen(3000);
